### ISSUE TITLE
Problem loading large images

### ISSUE THREAD

**Issue by ironstein0** [samtholiya/Vialogue#18]

**Comment by samtholiya** [comment]
Where is the problem exactly

**Comment by ironstein0** [comment]
1. take image (HDR image in my case) > Done > Takes a lot of time and freezes (but eventually the thumbnail is generated and is shown, but it feels as if the app froze)
2. Click on the slide and in the "add audio" activity, the image is not shown (black displayed). Logs show an error saying (image too large to be loaded)

**Comment by ironstein0** [comment]
Mostly, the second error can be solved by generating a thumbnail to be displayed (instead of the entire image) in the add audio activity
